### ISSUE TITLE
Is there a way to get the torque data using the simple message?

### ISSUE THREAD

**Issue by nexus1203** [tingelst/moto#17]
What I am trying to retrieve is actually a MotoRos function from the ControlGroup.h [torque data](https://github.com/ros-industrial/motoman/blob/7860ff545106d98ed6a3fa0121f2fb60891f69bd/motoman_driver/MotoPlus/CtrlGroup.c#L454-L477) using Ros_CtrlGroup_GetTorque function. Could you please guide me on how to achieve this using simple message?

**Comment by tingelst** [comment]
I dont think that this is supported on the MotoROS side as of now. You will have to for example modify the state server, using MotoPlus, to send effort data. After this is done it should be straight forward to read the effort data on the Python side.

**Comment by gavanderhoorn** [comment]
For context: https://github.com/ros-industrial/motoman/discussions/508.
