### ISSUE TITLE
enable robot is not implemented yet?

### ISSUE THREAD

**Issue by Njima1572** [tingelst/moto#2]
I saw a mention about `m.motion.enable_robot()` to start the robot, but didn't find the corresponding function anywhere in the repo.

Is it still under development??  

P.S. I really appreciate the work you did with this and am willing to contribute with my best effort.

**Comment by tingelst** [comment]
That method is not there now. I have updated the README file. 

It is enough to start the trajectory mode by: `m.motion.start_trajectory_mode()`
