### ISSUE TITLE
Difficulties connecting to RealTimeMotionServerSim() 

### ISSUE THREAD

**Issue by eastSpawn** [tingelst/moto#5]
I have been trying to run the real-time motion server using the examples:  test_moto_rt_motion_simulation.py and test_moto.py (replacing the IP with localhost)

When I run them I get this on the server side:

```
INFO:root:Waiting for connection
INFO:root:Got connection from ('127.0.0.1', 64822)
<socket.socket fd=568, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 50243), raddr=('127.0.0.1', 64822)>
INFO:root:Waiting for connection
```

and this on the client side:
```
ConnectionRefusedError: [WinError 10061] Kan ikke koble til fordi målmaskinen avslo tilkobling
```
The connection port does not seem to correspond with the TCP port.

Does anyone know how to deal with this issue?

**Comment by tingelst** [comment]
Have you started the moto sim server?

TCP connections are set up on other ports than the port you specify. This is normal behaviour.

For your use case you should focus on test_moto.py

**Comment by eastSpawn** [comment]
I have been trying with the test_moto_rt_motion_simulation.py example, which I believe is running the server?

```
sim = RealTimeMotionServerSim()
sim.start()

while True:
    pass
```

**Comment by tingelst** [comment]
use the `sim.py` example. 

All code related to realtime control can be considered experimental and should not be used as of now.

**Comment by eastSpawn** [comment]
Alright

Sadly I'm still struggling with getting a connection.

This is the code I'm running now instead:

From sim.py
```
from moto.sim.motosim import ControlGroupSim, MotoSim

logging.basicConfig(level=logging.DEBUG)
m = MotoSim("localhost", [ControlGroupSim(0, 6, [0.0] * 6)])
m.start()
while True:
    pass
```

From test_moto.py
```
m = Moto(
    "localhost",
    [
        ControlGroupDefinition(
            groupid="robot",
            groupno=0,
            num_joints=6,
            joint_names=[
                "joint_1_s",
                "joint_2_l",
                "joint_3_u",
                "joint_4_r",
                "joint_5_b",
                "joint_6_t",
            ],
        ),
        ControlGroupDefinition(
            groupid="positioner",
            groupno=1,
            num_joints=2,
            joint_names=["joint_1", "joint_2",],
        ),
    ],
    start_motion_connection=True,
    start_state_connection=True,
)
```

**Comment by tingelst** [comment]
In terminal 1 run `python -i sim.py`

Then in terminal 2 run:

```python
from moto import motion_connection
from moto import Moto, ControlGroupDefinition
from moto.simple_message import (
    JointFeedbackEx,
    JointTrajPtExData,
    JointTrajPtFull,
    JointTrajPtFullEx,
    ValidFields,
)

import time
import numpy as np
import copy

m = Moto(
    "localhost",
    [
        ControlGroupDefinition(
            groupid="robot",
            groupno=0,
            num_joints=6,
            joint_names=[
                "joint_1_s",
                "joint_2_l",
                "joint_3_u",
                "joint_4_r",
                "joint_5_b",
                "joint_6_t",
            ],
        ),
    ],
    start_motion_connection=True,
    start_state_connection=True,
)


robot = m.control_groups["robot"]

time.sleep(1)


robot_joint_feedback: JointFeedbackEx = m.state.joint_feedback(groupno=0)

p0 = JointTrajPtFullEx(
    number_of_valid_groups=1,
    sequence=0,
    joint_traj_pt_data=[
        JointTrajPtExData(
            groupno=0,
            valid_fields=ValidFields.TIME | ValidFields.POSITION | ValidFields.VELOCITY,
            time=0.0,
            pos=robot_joint_feedback.pos,
            vel=[0.0] * 10,
            acc=[0.0] * 10,
        ),
    ],
)

p1 = JointTrajPtFullEx(
    number_of_valid_groups=1,
    sequence=1,
    joint_traj_pt_data=[
        JointTrajPtExData(
            groupno=0,
            valid_fields=ValidFields.TIME | ValidFields.POSITION | ValidFields.VELOCITY,
            time=5.0,
            pos=np.deg2rad([10.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]),
            vel=[0.0] * 10,
            acc=[0.0] * 10,
        ),
    ],
)

```

**Comment by eastSpawn** [comment]
I just did _exactly_ that, and it is still not working for me.

```
C:\Users\user\Meta\moto>python -i sim.py
[motion_server]: Waiting for connection
[state_server]: Waiting for connection
[io_server]: Waiting for connection
>>>
```

and running the provided code I get:
```
Traceback (most recent call last):
  File "C:\Users\user\Meta\moto\test_moto_a.py", line 15, in <module>
    m = Moto(
  File "C:\Users\user\Meta\moto\moto\__init__.py", line 153, in __init__
    self._motion_connection.start()
  File "C:\Users\user\Meta\moto\moto\simple_message_connection.py", line 45, in start
    self._tcp_client.connect()
  File "C:\Users\user\Meta\moto\moto\simple_message_connection.py", line 31, in connect
    self._socket.connect(self._address)
ConnectionRefusedError: [WinError 10061] Kan ikke koble til fordi målmaskinen avslo tilkobling

Process returned 1 (0x1)        execution time : 2.500 s
```

Sorry for all the trouble..

**Comment by gavanderhoorn** [comment]
> [WinError 10061] Kan ikke koble til fordi målmaskinen avslo tilkobling

Windows firewall?

**Comment by eastSpawn** [comment]
That makes sense. 

I tried adding a firewall rule to allow all local TCP/UDP connections, but it still seems to reject the connection. I will continue digging in these directions a bit more.

Thanks for all the help!

**Comment by gavanderhoorn** [comment]
> I tried adding a firewall rule to allow all local TCP/UDP connections, but it still seems to reject the connection. I will continue digging in these directions a bit more.

I'd suggest doing an easy test: completely disable the firewall, then see whether it works.

If it does -> it's your firewall configuration.

If it still doesn't work -> no point in looking at the firewall again.

Then re-enable the firewall.

**Comment by eastSpawn** [comment]
I would love to do that (been trying), but I don't seem to have the right permissions on my work computer:

![image](https://user-images.githubusercontent.com/13307273/113851463-d2f61600-979b-11eb-87c3-f87619211abf.png)

Unless there's a way around it..

**Comment by gavanderhoorn** [comment]
No, not that I know of.

Perhaps get in touch with your (network) admin.

**Comment by eastSpawn** [comment]
I've finally had the opportunity to run the code on my own computer. It seems to work properly now. Thank you for all the help!

**Comment by tingelst** [comment]
> I've finally had the opportunity to run the code on my own computer. It seems to work properly now. Thank you for all the help!

This is good to hear! What steps did you take to make it work?

**Comment by eastSpawn** [comment]
It worked right off the bat! So no particularly interesting insight was gained, sadly.

But it would make sense if it had something to do with some firewall or networking setting on my work computer.

I might try again at a later date. Thanks again
